### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by PandaIN95** [Tomato6966/lavalink-client#11]
How am i suppose to skip the current playing track when there is no queue ?? i mean i can use .seek(track.duration) but is there any better way to do it ??

**Comment by Tomato6966** [comment]
If there are no tracks in queue, and then call skip nothing it throws error because you shouldn't skip that.

U have the options to:
Delete the player on lavalink, without disconnecting from the channel

Or delete the player on lavalink, with disconnecting

Or stop playing, for that i forgot to add the method player.stop() which just does player.play({ encodedTrack: null})

**Comment by Tomato6966** [comment]
![image](https://github.com/Tomato6966/lavalink-client/assets/68145571/e38c6017-3307-4e41-a271-9d6352df5d33)
In that image you can see that `player.play({ encodedTrack: null })` is technically just telling lavalink server "stop the track". which then executes trackend (and the wrapper internally autoSkip's to the next track), if there is no next track -> queue will end.

If you really need to "stop" the player after the last track without destroying nor deleting the player. Think about it..

**Comment by Tomato6966** [comment]
`player.play({ track: LavalinkTrack, position: numberInMs })`

startTime is wrong variable, it's called "position" to probably cover how lavalink names things... (startTime was erela.js thing, position is lavalink thing)
you should see it in intellisense...

you can use track to define which track, but you don't need to, if the track is in player.queue.tracks[0]

**Comment by Tomato6966** [comment]
this feature got disabled intentionally for multi-node automation and support.
as if you search on a different node which is not the player node you cannot play the tracks.

However you can do `node.search()` aka `manager.nodeManager.nodes.get("ID").search({ query: string, source: string }, requester);`

**Comment by Tomato6966** [comment]
Thats a very specific usecase

U can adjust the player.queue.previous and then execute await player.queue.utils.save()

Its not ment to only. Hold unique tracks as thats then not a real previous handler

**Comment by Tomato6966** [comment]
Please ask that in lavalink not in a client which just sends requests to lavalink.
