### ISSUE TITLE
Module is not resolved correctly in WebStorm

### ISSUE THREAD

**Issue by MeridianGH** [Tomato6966/lavalink-client#12]
The module is not resolved correctly and listed as "not installed" in WebStorm, even tho it is installed correctly and listed in `package.json`:

![grafik](https://github.com/Tomato6966/lavalink-client/assets/50270402/17cb57cf-592b-4b47-acb4-4b958dfde2a7)

This is a bit problematic since types (or type hints) are not imported because of this.
The package is however still working as usual.

Any idea why this might happen?

**Comment by Tomato6966** [comment]
I certainly do not have an idea.

**Comment by MeridianGH** [comment]
I did some testing and it seems it has something to do with the way the structures are exported.

If I manually place an `index.js` in the module's root folder (i.e. not in /dist), WebStorm correctly recognizes it as a module.

I can then use
```js
import * as lavalink-client from 'lavalink-client'
```
and then access the structures using
```js
new lavalink-client.__esModule.LavalinkManager(...)
```
\
I guess this is either due to the module's Typescript configuration or the way exports are handled.
Either way, this is slightly above me since I never really worked with Typescript before.

**Comment by Tomato6966** [comment]
I think it has to do something with webstorm

**Comment by MeridianGH** [comment]
Most certainly, yes. Although I don't think this is a commonly known issue and other module seem to work fine.

Importing from `lavalink-client/dist` also works fine.

I think it has something to do with the way the module is exported to `/dist`

Seems like it works fine now.

**Comment by Tomato6966** [comment]
![image](https://github.com/Tomato6966/lavalink-client/assets/68145571/949700d9-ad15-412a-8331-aa70cb7d5d00)
Maybe it's because of the package.json

**Comment by MeridianGH** [comment]
Could be. You could try exporting the individual parts directly in the root folder, i.e. just `/cjs/index.js` or `/types/index.d.ts`.

That doesn't solve the issue tho, that the regular index.js is still in the `/dist` subdirectory...

**Comment by Tomato6966** [comment]
I am exporting the projects correclty

if you have module enabled it is getting imported through dist/esm
if not aka you code in cjs, it uses main..
