### ISSUE TITLE
URL is not replaced correctly when using standard ports

### ISSUE THREAD

**Issue by MeridianGH** [Tomato6966/lavalink-client#14]
Hey again, I found an issue when debugging a bit.

When using standard ports (in my test 443, port 80 probably throws the same error) I get an error when trying to skip songs.

Turns out, that the `Node.updatePlayer` function constructs an URL using `new URL(...)` and therefore loses the port (because it is standard). When trying to replace the `poolAddress`, the substring can't be replaced due to the missing port.
See: [here](https://github.com/Tomato6966/lavalink-client/blob/1c6614668e22e9da000b98ed1c8165adc7e19d62/src/structures/Node.ts#L305)

A possible fix would be instead of using `.toString().replace(...)` to just get the URL parts manually:
```js
r.path = url.pathname + url.search;
```

There may be more places where this might be an issue, but I haven't come around to testing all cases.

**Comment by Tomato6966** [comment]
I already pushed an fix for that in the past hugh, ill look into it tmr thx

**Comment by MeridianGH** [comment]
Yeah, my bad. I haven't updated NPM in a while. The recent fix resolved this issue.
