### ISSUE TITLE
I can't hear the bot but he is "playing"

### ISSUE THREAD

**Issue by KasaiKonoru** [Tomato6966/lavalink-client#20]
![image](https://github.com/Tomato6966/lavalink-client/assets/45830738/cfa817f1-408f-44d1-a8b9-757619954b27)
I have also no errors in console. But Position is changing all the time. :c

Lavalink Logs: 
![image](https://github.com/Tomato6966/lavalink-client/assets/45830738/7b2d606f-7ee0-4ef2-95af-0dae7b455b6a)

**Comment by Tomato6966** [comment]
Did you provide voice intents

Do you properly listen to the raw event?

Try the advanceOptions for debugoptions noAudio

**Comment by KasaiKonoru** [comment]
Yeah Its listen to the raw event. And voice intents are enabled

**Comment by KasaiKonoru** [comment]
you mean Guild_Voice_States intent, right?

**Comment by KasaiKonoru** [comment]
And how you mean "Try the advanceOptions for debugoptions noAudio" I don't understand how.

**Comment by KasaiKonoru** [comment]
Ahhh nvm it works now. My bad. 

But now I tried custom url mp3's but I get the error: "Not valid." Where I can enable custom url plays?

**Comment by Tomato6966** [comment]
http urls needs to be enabled in application.yml from lavalink...

**Comment by Tomato6966** [comment]
As you can see in the example bot: https://github.com/Tomato6966/lavalink-client/blob/main/testBot/index.ts
you can add the `advancedOptions.debugOptions.noAudio = true`

```js
client.lavalink = new LavalinkManager({
 // ...
  advancedOptions: {
        debugOptions: {
            noAudio: true
        }
    }
})

**Comment by KasaiKonoru** [comment]
Thx for your response...
> http urls needs to be enabled in application.yml from lavalink...

yeah I enabled "local" and "http" (I set them to true)

**Comment by KasaiKonoru** [comment]
`plugins:
  lavasrc:
    providers: # Custom providers for track loading. This is the default
      # - "dzisrc:%ISRC%" # Deezer ISRC provider
      # - "dzsearch:%QUERY%" # Deezer search provider
      - "ytsearch:\"%ISRC%\"" # Will be ignored if track does not have an ISRC. See https://en.wikipedia.org/wiki/International_Standard_Recording_Code
      - "ytsearch:%QUERY%" # Will be used if track has no ISRC or no track could be found for the ISRC
      #  you can add multiple other fallback sources here
    sources:
      spotify: true # Enable Spotify source
      applemusic: false # Enable Apple Music source
      deezer: false # Enable Deezer source
      yandexmusic: false # Enable Yandex Music source
      flowerytts: false # Enable Flowery TTs source
      youtube: true # Enable YouTube search source (https://github.com/topi314/LavaSearch)
      local: true
      http: true
    spotify:
      clientId: ""
      clientSecret: ""
      countryCode: "US" # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      playlistLoadLimit: 6 # The number of pages at 100 tracks each
      albumLoadLimit: 6 # The number of pages at 50 tracks each
    applemusic:
      countryCode: "US" # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      mediaAPIToken: "..." # apple music api token
      playlistLoadLimit: 6 # The number of pages at 300 tracks each
      albumLoadLimit: 6 # The number of pages at 300 tracks each
    deezer:
      masterDecryptionKey: "your master decryption key" # the master key used for decrypting the deezer tracks. (yes this is not here you need to get it from somewhere else)
    yandexmusic:
      accessToken: "your access token" # the token used for accessing the yandex music api. See https://github.com/TopiSenpai/LavaSrc#yandex-music
    flowerytts:
      voice: "default voice" # (case-sensitive) get default voice here https://flowery.pw/docs/flowery/tts-voices-v-1-tts-voices-get
      translate: false # whether to translate the text to the native language of voice
      silence: 0 # the silence parameter is in milliseconds. Range is 0 to 10000. The default is 0.
      speed: 1.0 # the speed parameter is a float between 0.5 and 10. The default is 1.0. (0.5 is half speed, 2.0 is double speed, etc.)
      audioFormat: "mp3" # supported formats are: mp3, ogg_opus, ogg_vorbis, aac, wav, and flac. Default format is mp3

server: # REST and WS server
  port: 2444
  address: localhost
lavalink:
  server:
    password: "Raccoon"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: false
      http: true
      local: true
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is the best quality but is the most expensive on the CPU.
    resamplingQuality: MEDIUM # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 8000 # The threshold for how long a track can be stuck. A track is stuck if it does not return any audio data.
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000`

**Comment by KasaiKonoru** [comment]
[application.txt](https://github.com/Tomato6966/lavalink-client/files/14359327/application.txt)
This are my settings. (I changed it to txt because github dont want yaml files)

**Comment by 1Lucas1apk** [comment]
I noticed that in your Lavalink log, there is no voice information
You added the sendRawData() function?
https://github.com/Tomato6966/lavalink-client/blob/main/testBot/events/raw.ts

**Comment by KasaiKonoru** [comment]
all is working, but only http requests not. 

And I have a question: How I can search for track without an active player? I want to search first and then create the player, whenj something is found.

**Comment by KasaiKonoru** [comment]
Nvm http is working. A lavalink dev said me: "spaces need to be properly encoded in urls". Now it works. But how I can search for tracks without an active player?

**Comment by 1Lucas1apk** [comment]
By node: https://github.com/Tomato6966/lavalink-client/blob/f0007b83bd1cb2811b3efc69b28f9d5ed15b0591/src/structures/Node.ts#L307

**Comment by KasaiKonoru** [comment]
Ahh you mean something like that?
`client.manager.nodeManager.nodes.get("main").search()`

**Comment by 1Lucas1apk** [comment]
Yes, I hadn't seen that one either :)

**Comment by KasaiKonoru** [comment]
lol xD
But whats the best method?

**Comment by Tomato6966** [comment]
The best method is to search by creating a player.
That way you don't have to mind for "checking if the song searched on node X is the same as the node of the player created later"

The player creation is almost instant, so no reason not to create a player.

```js
const player = client.manager.createPlayer({ guildId: "" }); 
const res = await player.search({ query, source }, requesterUser);
```
You can create player without providing the voiceChannelId too... 
if you want him to connect later without re-creating it, simply do: 
```
player.options.voiceChannelId = "vcId";
await player.connect();
```

**Comment by KasaiKonoru** [comment]
Okay thanks
