### ISSUE TITLE
autoPlayFunction not triggering

### ISSUE THREAD

**Issue by Faf4a** [Tomato6966/lavalink-client#21]
Small question, is `autoPlayFunction` not supposed to trigger when only one song is added, meaning there would be no queue and only the current playing song?

Or could it be that I'm doing something wrong, because when I add two songs (current, and one to queue) it triggers after the second song finishes playing.

For better understanding:

Doesn't trigger:
```js
Queue {
  tracks: [],
  previous: [],
  current: [Object],
  options: [Object],
  guildId: 'some guild id',
  QueueSaver: [QueueSaver],
  managerUtils: [ManagerUtils],
  queueChanges: null,
  utils: [Object]
}
```

Triggers:
```js
Queue {
  tracks: [],
  previous: [Array],
  current: [Object],
  options: [Object],
  guildId: 'some guild id',
  QueueSaver: [QueueSaver],
  managerUtils: [ManagerUtils],
  queueChanges: null,
  utils: [Object]
}
```

**Comment by Faf4a** [comment]
However this works,
```js
    manager.on("queueEnd", async (player) => {
      if (player.get("autoplay") === false) return;
      await autoPlayFunction(player, player.queue.previous[0]);
    });
```

Regardless on queue length.

**Comment by Tomato6966** [comment]
It triggers AUTOMATICALLY (when provided to the manageroptions), you don't have to call the function by yourself.
It triggers when no songs are in the queue and the current song ends.

**Comment by Tomato6966** [comment]
As you can see in the examplebot: https://github.com/Tomato6966/lavalink-client/blob/main/testBot/index.ts#L72 this is how you provide it

```js
async function autoPlayFunction(player, lastPlayedTrack) {
 if(player.get("autoplay") === false) return;
 // somehow get the next song
 await player.queue.add(nextSong); //if the await of the function is done, and there is no more song in player.queue.tracks then it will emit queueEnd, else it will play it!
// so all you need to do is in that function, decide wether to add a track or not. also it's your choice how many tracks you want to add
}
client.lavalink = new LavalinkManager({
    // ....
    playerOptions: {
        onEmptyQueue: {
            autoPlayFunction: autoPlayFunction,
        },
    },
});

```

**Comment by Tomato6966** [comment]
You can see in the source code how that works https://github.com/Tomato6966/lavalink-client/blob/main/src/structures/Node.ts#L915

If you want to make a autoplayfunction all by yourself, you can do that too, but that's not client issue then.

**Comment by Faf4a** [comment]
> You can see in the source code how that works https://github.com/Tomato6966/lavalink-client/blob/main/src/structures/Node.ts#L915
> 
Thanks for the heads up, seems to work now.

No idea what caused, well whatever it works now.

![](https://i.imgur.com/0qwdx84.png)
