### ISSUE TITLE
player.destroy() destroys shard and manager

### ISSUE THREAD

**Issue by siy-uuu** [Tomato6966/lavalink-client#28]
A trackStuck event occurred and I ordered player.destroy(); and it destroys my shard

https://sourceb.in/hObR3xz7Rg
https://sourceb.in/B7m1sklQ2n

# trackStuck.js
```js
module.exports = async (player, track, payload) => {
    return player.destroy();
};
```

**Comment by Tomato6966** [comment]
probably because you load the event like this:

eventFunction(client, player, track, payload);

and thus your "player" is really just "botclient"
