### ISSUE TITLE
TypeError: ManagerUitls.buildTrack is not a function

### ISSUE THREAD

**Issue by SomboyTiger** [Tomato6966/lavalink-client#3]
var  { ManagerUitls } = require(`lavalink-client`)
**buildTrack**

TypeError: ManagerUitls.buildTrack is not a function

**Comment by Tomato6966** [comment]
ManagerUtils is a class and you can only access it's non-static methods, like buildTrack, after initializing the class.
```js
const utils = new ManagerUtils(manager);
utils.buildTrack()
```
or just do

```js
client.lavalink.utils.buildTrack()
```

cause ManagerUtils already exists on LavalinkManager class...

**Comment by Tomato6966** [comment]
[Documentation Reference](https://lc4.gitbook.io/lavalink-client/docs/lavalinkmanager#.utils)

Here is an example:
```js
const { LavalinkManager, ManagerUtils } = require("lavalink-client");

client.lavalink = new LavalinkManager({ ...YourLavalinkManagerOptions });

// now access the ManagerUtils
client.lavalink.utils.buildTrack(trackData, requesterUser);

// create your own utils class
client.managerUtils = new ManagerUtils(client.lavalink) // useless... cause you can just do client.lavalink.utils!
```

However, I don't know why you need to exec. buildTrack?
-> the methods: `player.search()`, `player.nodedecode.singleTrack()`, `player.node.decode.multipleTracks()`, and `player.lavaSearch()` all return already builded Tracks, which means the manager executes buildTrack internally.

**Comment by SomboyTiger** [comment]
Can I add a plugin? (◕‿◕)
