### ISSUE TITLE
[Suggestion] Support for LavaLyrics

### ISSUE THREAD

**Issue by zoli456** [Tomato6966/lavalink-client#31]
Topi recently released a new [plugin](https://github.com/topi314/LavaLyrics) for Lavalink. I think It would be good to have built-in support for the Lava Lyrics plugin.

**Comment by Tomato6966** [comment]
I will implement the latest plugin features yet again.
It's possible to be used with your own implementation tho.

Thanks for the suggestion

**Comment by Tomato6966** [comment]
just so you know, you can use it by yourself just do a player.node.request("...")
