### ISSUE TITLE
[Suggestion] Export interfaces 

### ISSUE THREAD

**Issue by EvilG-MC** [Tomato6966/lavalink-client#32]
I do not know if there is a possibility to export the following interfaces:

- [node events interface](https://github.com/Tomato6966/lavalink-client/blob/main/src/structures/NodeManager.ts#L10)
- [manager events interface](https://github.com/Tomato6966/lavalink-client/blob/main/src/structures/LavalinkManager.ts#L93)

Why? Usually for typescript users, to be able to use the types correctly to make an event handler, because you need to create the types manually and that is not very maintainable.

**Comment by Tomato6966** [comment]
you wouldn't need to access those interfaces as they are getting suggested if you write the "on" or "once" statement
![image](https://github.com/Tomato6966/lavalink-client/assets/68145571/cb8ce2eb-80cd-4edc-86a3-4f1ca5305374)

![image](https://github.com/Tomato6966/lavalink-client/assets/68145571/6080776c-9999-4b92-bf0b-f471dc421d92)

But i can export them if that makes you happier

**Comment by EvilG-MC** [comment]
I would really appreciate it.

**Comment by EvilG-MC** [comment]
Thank you!
