### ISSUE TITLE
ManagerPlayerOptions missing types specified in documentation 

### ISSUE THREAD

**Issue by SemiMute** [Tomato6966/lavalink-client#35]
https://lc4.gitbook.io/lavalink-client/docs/lavalinkmanager/manager-options/managerplayeroptions

Documentation shows types allow for more options, but interface is missing them (Such as onDisconnect, onEmptyQueue)

Edit: Tried on both v2.2.0 and v2.1.3 and both are missing the options on interface

**Comment by Tomato6966** [comment]
https://tomato6966.github.io/lavalink-client/

Please refer to the auto generated documentation
I sadly don't have enough time to complete the custom docs.

**Comment by Tomato6966** [comment]
https://tomato6966.github.io/lavalink-client/interfaces/LavalinkManager.ManagerOptions.html
