### ISSUE TITLE
Invalid track identifier in SoundCloud source

### ISSUE THREAD

**Issue by Alexinhans** [Tomato6966/lavalink-client#36]
`track.info.identifier` (track ID) returns full URL instead of ID when using SoundCloud as source. 

![image](https://github.com/Tomato6966/lavalink-client/assets/103999185/5606529a-8a74-40df-b2e6-91c8b9d0476c)
![Screenshot 2024-06-22 131726](https://github.com/Tomato6966/lavalink-client/assets/103999185/e6d12da9-49f6-4afb-a448-721b3aeabdcc)

additional context:
lavalink-client version: v2.2.0

**Comment by Tomato6966** [comment]
this is what lavalink returns, lavalink-client doesn't modify tracks at all.

**Comment by Alexinhans** [comment]
Oh cool Imma report this to lavalink

**Comment by Tomato6966** [comment]
It's not necessary an issue tho.. it's just how it is
