### ISSUE TITLE
command autoplay lavalink v4 

### ISSUE THREAD

**Issue by Yanishamburger** [Tomato6966/lavalink-client#38]
Hello, I come to ask you how to make an autoplay command on version 4 of lavalink because I can't find how it works.
King regards

**Comment by EvilG-MC** [comment]
You should check this:

[Function](https://github.com/Tomato6966/lavalink-client/blob/main/testBot/Utils/OptionalFunctions.ts#L18-L60)
[Index](https://github.com/Tomato6966/lavalink-client/blob/main/testBot/index.ts#L71)

And in the command you only need to change values.

**Comment by Yanishamburger** [comment]
Ok thx
