### ISSUE TITLE
How to use it in aoi.js

### ISSUE THREAD

**Issue by CycloneAddons** [Tomato6966/lavalink-client#4]
Make function of aoi.js inside it using customFunction

**Comment by fb-sean** [comment]
What

**Comment by CycloneAddons** [comment]
> What

Bro Aoi.js Is A Package like discordjs

**Comment by fb-sean** [comment]
1. I know what Aoijs is
2. Its not like djs it is a framework on top of djs 
3. What do you actually want be more specific

**Comment by Tomato6966** [comment]
I wouldn't say you can make it work with aoijs simply cause you can't use it as strings only

**Comment by CycloneAddons** [comment]
![Uploading Screenshot_2023-08-22-20-22-51-543_com.replit.app.jpg…]()

**Comment by CycloneAddons** [comment]
![Screenshot_2023-08-22-20-22-51-543_com replit app](https://github.com/Tomato6966/lavalink-client/assets/90061864/3777e096-d510-4b8c-a32d-585056d23236)
It say that how to give shards ??? With aoi.js

**Comment by fb-sean** [comment]
> ![Screenshot_2023-08-22-20-22-51-543_com replit app](https://user-images.githubusercontent.com/90061864/262393762-3777e096-d510-4b8c-a32d-585056d23236.jpg) It say that how to give shards ??? With aoi.js

sendToShard: (guildId, payload) => client.guilds.cache.get(guildId)?.shard?.send(payload),

You need to make "client" the djs client since aoijs use djs
