### ISSUE TITLE
Export Manager Types

### ISSUE THREAD

**Issue by NedcloarBR** [Tomato6966/lavalink-client#41]
Good afternoon! I'm wanting to use this library as a core for [@necord/lavalink](https://github.com/necordjs/lavalink) but for this to occur it is necessary that the Manager typing be exported in [index.ts](https://github.com/Tomato6966/lavalink-client/blob/main/src/index.ts)
```diff
+ export * from "./structures/Types/Manager";
```
I'll create the PR for this issue

**Comment by Tomato6966** [comment]
Will ciome with v2.3.1. (in the next few hours)
