### ISSUE TITLE
feat: create debug event

### ISSUE THREAD

**Issue by NedcloarBR** [Tomato6966/lavalink-client#43]
For handling the [debug options](https://github.com/Tomato6966/lavalink-client/blob/main/src/structures/Types/Manager.ts#L182-L194) instead of direct logging

also i can create a PR

**Comment by Tomato6966** [comment]
wdym the logs are only ment to be turned on if smt isn't working so you don'T have to debug the internal code

**Comment by EvilG-MC** [comment]
I want to think, he means to create a debug event to send logs

Like:

```js
client.lavalink.on("debug", (message) => console.log(message));
```

**Comment by Tomato6966** [comment]
This makes not really sense for lavalink-client, i'd rather create a function on manager Options like
internalLogging(module:"node"|"player"|"utils"|"manager"|"filters", { error: null|Error, info: string })

But ofc. i could also add an event, i'd call it not debug tho, maybe "internal" but also debug makes sense, i'm just thinking in a way that it's clear that it's only for the client, and not related to lavalink at all

**Comment by EvilG-MC** [comment]
I would have a bit of a related with the manager... But it would be a bit nice to have that event, but if you don't see it necessary, it's okay

**Comment by NedcloarBR** [comment]
> I think, he means to create a debug event to send logs
> 
> Like:
> 
> ```js
> client.lavalink.on("debug", (message) => console.log(message));
> ```

Yeah is that
I think thats is useful for logging controll like users with custom logger just for styled terminal or functional custom loggers with transcript

**Comment by EvilG-MC** [comment]
I guess there is a good point in wanting to use some custom logger

**Comment by Tomato6966** [comment]
Version 2.3.3 released

This introduces a first version of the debug event

I added a bunch of events
```ts
export enum DebugEvents {
    SetSponsorBlock = "SetSponsorBlock",
    DeleteSponsorBlock = "DeleteSponsorBlock",
    TrackEndReplaced = "TrackEndReplaced",

    AutoplayNoSongsAdded = "AutoplayNoSongsAdded",
    AutoplayThresholdSpamLimiter = "AutoplayThresholdSpamLimiter",
    TriggerQueueEmptyInterval = "TriggerQueueEmptyInterval",
    QueueEnded = "QueueEnded",
    TrackStartNewSongsOnly = "TrackStartNewSongsOnly",
    TrackStartNoTrack = "TrackStartNoTrack",

    ResumingFetchingError = "ResumingFetchingError",

    PlayerUpdateNoPlayer = "PlayerUpdateNoPlayer",
    PlayerUpdateFilterFixApply = "PlayerUpdateFilterFixApply",
    PlayerUpdateSuccess = "PlayerUpdateSuccess",

    HeartBeatTriggered = "HeartBeatTriggered",
    NoSocketOnDestroy = "NoSocketOnDestroy",
    SocketTerminateHeartBeatTimeout = "SocketTerminateHeartBeatTimeout",

    TryingConnectWhileConnected = "TryingConnectWhileConnected",

    LavaSearchNothingFound = "LavaSearchNothingFound",
    SearchNothingFound = "SearchNothingFound",

    ValidatingBlacklistLinks = "ValidatingBlacklistLinks",
    ValidatingWhitelistLinks = "ValidatingWhitelistLinks",

    TrackErrorMaxTracksErroredPerTime = "TrackErrorMaxTracksErroredPerTime",
    TrackStuckMaxTracksErroredPerTime = "TrackStuckMaxTracksErroredPerTime",

    PlayerDestroyingSomewhereElse = "PlayerDestroyingSomewhereElse",
    PlayerCreateNodeNotFound = "PlayerCreateNodeNotFound",
    PlayerPlayQueueEmptyTimeoutClear = "PlayerPlayQueueEmptyTimeoutClear",
    PlayerPlayWithTrackReplace = "PlayerPlayWithTrackReplace",
    PlayerPlayUnresolvedTrack = "PlayerPlayUnresolvedTrack",
    PlayerPlayUnresolvedTrackFailed = "PlayerPlayUnresolvedTrackFailed",
    PlayerVolumeAsFilter = "PlayerVolumeAsFilter",
    BandcampSearchLokalEngine = "BandcampSearchLokalEngine",
    PlayerChangeNode = "PlayerChangeNode",

    BuildTrackError = "BuildTrackError",
    TransformRequesterFunctionFailed = "TransformRequesterFunctionFailed",
    GetClosestTrackFailed = "GetClosestTrackFailed",
    PlayerDeleteInsteadOfDestroy = "PlayerDeleteInsteadOfDestroy",
    FailedToConnectToNodes = "FailedToConnectToNodes",
    NoAudioDebug = "NoAudioDebug",
    PlayerAutoReconnect = "PlayerAutoReconnect"
}
```

This is how you can listen to them:
```js
client.lavalink.on("debug", (eventKey, eventData) => {
        // skip specific log
        if(eventKey === DebugEvents.NoAudioDebug && eventData.message === "Manager is not initated yet") return;
        // skip specific event log of a log-level-state "log"
        if(eventKey === DebugEvents.PlayerUpdateSuccess && eventData.state === "log") return;

        console.group("Lavalink-Client-Debug:");
        console.log("-".repeat(20));
        console.debug(`[${eventKey}]`);
        console.debug(eventData)
        console.log("-".repeat(20));
        console.groupEnd();
    });
```

Update Log:

## **Version 2.3.1**

- Fixed Export, where types of Manager weren't exported correctly
- Fixed Dist Folder containing old, left over not needed files

## **Version 2.3.2**
- Added Missing function calls for the QueueWatcher of tracksRemoved within the queue.remove() function:
- Added new DestroyReasons:
    - TrackStuckMaxTracksErroredPerTime
    - TrackErrorMaxTracksErroredPerTime
- Added new Prevention Systems for CrashbackLoop recognitions:
    - `this.NodeManager.LavalinkManager.options.playerOptions.maxErrorsPerTime`:
        - object: `{ threshold: number, maxAmount: number }` (set threshold to 0 or maxAmount to -1 to disable)
        - Default: `{ threshold: 10_000, maxAmount: 3 }`
        - If there are trackError or trackStuck Events > maxAmount within the given treshhold, the player will be destroyed prevent more errors and thus potential ratelimits.
    - `this.NodeManager.LavalinkManager.options.playerOptions.minAutoPlayMs`:
        - number: `10_000` (default)
        - If there is an AutoplayFunction, and it get's executed before that threshold, than it won't trigger the autoplay function again. *(this is ignored for when the player is skipped)*
        - This prevents autoplays from happeneing on a crashbackloop
        - Set to `0` to disable
- **Added new Event "debug":**
    - `LavalinkManager#debug(event:DebugEvents, data:{ state: "log" | "warn" | "error", message:string, functionLayer:string, error?:Error })`
    - This function Event will emit, when the following option is set to **` true `**: `LavalinkManager.options.advancedOptions.enableDebugEvents`
    - You can use the **` DebugEvents `**  Enum to listen to specific events and only show those you care
    - You can filter for the **` data.state `** to only show the certain log-level state
    - The **` functionLayer `** string will show you where the debug event was triggered from
    - The **` message `** string will show what is debugged
    - The **` error `** object will show you the error that happened, if there was one.
    - *This took quite some time to code, and i am sure there are still many logs you might want, feel free to open an issue or commit with an PR, if you think something is missing!*

**Comment by Tomato6966** [comment]
Please leave a review wether you like or not, feel free to add more debug logs via PR or suggestions by openign a ticket / messaging me on discord.

It took quite some time to setup just debug logs which i recommend to only use on a testing environment.
