### ISSUE TITLE
no sound 

### ISSUE THREAD

**Issue by AhmedMondo** [Tomato6966/lavalink-client#62]
![image](https://github.com/user-attachments/assets/1a282d96-05d6-4bce-a68c-885ace73a904)
im running the lavalink on VPS Linux server with IPv6 
and the bot running on my pc and it works well but when i move the bot into the VPS the sessionId not sent idk why 
i asked in lavalink's server and they said its from the client 
also latest version of lavalink-client

**Comment by AhmedMondo** [comment]
also tried that on another RDP Windows and same thing the sessionId is not sent

**Comment by Tomato6966** [comment]
Do you listen to the "sendRawData" function on the raw event?
Do you have the Voice intent enabled?
You can use the debugEvents option in the advanceOptions from the Manager, to enable the "debug" event.

**Comment by AhmedMondo** [comment]
Yeah i set everything 
Also the same code works on my local pc normally but when i copy the code to vps it doesn't

**Comment by AhmedMondo** [comment]
I will try debug

**Comment by Tomato6966** [comment]
If it works on your local machine but not on your remote machine it's not due to the library that's weird

**Comment by AhmedMondo** [comment]
If its not related to lavalink and not related to client so what is the issue

**Comment by AhmedMondo** [comment]
![image](https://github.com/user-attachments/assets/6f5a1cbd-f2dc-4596-b3d6-8f4086e94ea6)
this what is shown when i activated debugEvent

**Comment by Tomato6966** [comment]
The id you provide in manager.init, must be the bot's user id

**Comment by AhmedMondo** [comment]
thx fixed, its wierd btw
