### ISSUE TITLE
bug?: bot keep playing after NodeJS shutdown for a random time when using `node.updateSession()`

### ISSUE THREAD

**Issue by NedcloarBR** [Tomato6966/lavalink-client#72]
So the title kind of says it all
I'm testing the [resuming functions](https://github.com/Tomato6966/lavalink-client?tab=readme-ov-file#how-to-do-resuming) and I came across this

**Comment by EvilG-MC** [comment]
The purpose of the `updateSession` is to temporarily maintain the playback through the node on everything the bot reconnects.
