### ISSUE TITLE
player voice empty v2.4.0

### ISSUE THREAD

**Issue by orfox32** [Tomato6966/lavalink-client#75]
when someone leaves the channel the event playerVoiceStart, End and Cancel will trigger and leave the channel even though there is a people in the channel

**Comment by Tomato6966** [comment]
Thanks for reporting that, I will check it out and fix it, i think i know the issue maybe

**Comment by Tomato6966** [comment]
I will remove the feature again, i now know again why i didn't supported in initially

However i will add playerVoiceLeave and playerVoiceJoin events, so you can build smt like that yourself easily

**Comment by Tomato6966** [comment]
I removed the playerVoiceEmpty feature, and added the requested events for easier handling in your applications

    ~~- **`playerVoiceEmptyStart`** ➡️ `(player, timeoutMs) => {}`~~
    ~~*Triggered when the voice empty handler started (the timeout)*~~
    *Removed again because of memory overhall and not wanting to handle voice states*

    ~~- **`playerVoiceEmptyEnd`** ➡️ `(player) => {}`~~
    ~~*Triggered when the voice empty handler finished (successfully) and thus destroyed the player*~~
    *Removed again because of memory overhall and not wanting to handle voice states*

    ~~- **`playerVoiceEmptyCancel`** ➡️ `(player, userId) => {}`~~
    ~~*Triggered when the voice empty handler cancelled (e.g. when a user rejoined)*~~
    *Removed again because of memory overhall and not wanting to handle voice states*

    - **`playerVoiceJoin`** ➡️ `(player, userId) => {}`~~
    *Added instead of the playerVoiceEmpty handler, emitted when a user joins the player-vc while there is a player*
    *Allows you to inmplement a custom playerVoiceEmpty handler*

    - **`playerVoiceLeave`** ➡️ `(player, userId) => {}`~~
    *Added instead of the playerVoiceEmpty handler, emitted when a user leaves (or. switches away) the player-vc while there is a player*
    *Allows you to inmplement a custom playerVoiceEmpty handler*
