### ISSUE TITLE
Option to Remove "- Topic" from YouTube Authors

### ISSUE THREAD

**Issue by BENx2115** [Tomato6966/lavalink-client#84]
I have a feature request that I believe could be beneficial for many users. Would it be possible to add an optional setting (e.g., a boolean flag) in `playerOptions` or another relevant configuration area to remove "- Topic" from video author names when enabled?

For example:  
- Original author name: "Author Name - Topic"  
- With the option enabled: "Author Name"

This would provide a cleaner display of author names, particularly in scenarios where the topic suffix is not needed.

How this could be implemented: 
```js
.replace('- Topic', '').trim();
```

**Comment by 1Lucas1apk** [comment]
This does not need to be done on the client side.

"Author Name - Topic".split(" - ")[0];

**Comment by Tomato6966** [comment]
This you should do yourself with a util function like

function transformTrackAuthor(trackAuthor:string){
 return trackAuthor.replace('- Topic', '').trim();
}
